"""
MAHALAKSMI AIOS v1.0.6 - Knowledge Graph & GitHub Center Tests
Tests relationship mapping and git operations
"""
import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.intelligence.knowledge_graph import (
    get_knowledge_graph,
    KnowledgeGraph,
    NodeType,
    RelationType,
    GraphNode,
    GraphEdge
)
from app.development.github_center import (
    get_github_center,
    GitHubCenter
)


class TestResults:
    def __init__(self):
        self.passed = 0
        self.failed = 0
        self.errors = []
    
    def record(self, name: str, passed: bool, message: str = ""):
        if passed:
            self.passed += 1
            print(f"  ✅ {name}")
        else:
            self.failed += 1
            self.errors.append(f"{name}: {message}")
            print(f"  ❌ {name} - {message}")


async def test_knowledge_graph_initialization(results: TestResults):
    """Test knowledge graph initialization."""
    print("\n🕸️ TEST: Knowledge Graph Initialization")
    print("-" * 40)
    
    kg = get_knowledge_graph()
    
    results.record(
        "Knowledge Graph Created",
        kg is not None
    )
    
    results.record(
        "Database Initialized",
        kg.db is not None
    )
    
    results.record(
        "Graph Initialized",
        kg._initialized
    )
    
    return kg


async def test_graph_nodes_creation(results: TestResults, kg: KnowledgeGraph):
    """Test creating graph nodes."""
    print("\n📦 TEST: Graph Nodes Creation")
    print("-" * 40)
    
    # Add a test node
    node = kg.add_node(
        node_id="TEST-NODE-001",
        node_type=NodeType.ENTITY,
        name="Test Entity",
        properties={"test": "value"}
    )
    
    results.record(
        "Node Created",
        node is not None and node.node_id == "TEST-NODE-001"
    )
    
    # Verify node exists
    retrieved = kg.db.get_node("TEST-NODE-001")
    results.record(
        "Node Retrieved",
        retrieved is not None and retrieved.name == "Test Entity"
    )
    
    return kg


async def test_graph_edges_creation(results: TestResults, kg: KnowledgeGraph):
    """Test creating graph edges."""
    print("\n🔗 TEST: Graph Edges Creation")
    print("-" * 40)
    
    # Create source node
    source = kg.add_node(
        node_id="SOURCE-001",
        node_type=NodeType.PRODUCT,
        name="Source Product"
    )
    
    # Create target node
    target = kg.add_node(
        node_id="TARGET-001",
        node_type=NodeType.REVENUE,
        name="Revenue Engine"
    )
    
    # Create edge
    edge = kg.add_edge(
        source_id="SOURCE-001",
        target_id="TARGET-001",
        relation_type=RelationType.GENERATED_BY,
        weight=1.0
    )
    
    results.record(
        "Edge Created",
        edge is not None and edge.source_id == "SOURCE-001"
    )
    
    # Verify edge exists
    edges = kg.get_edges(source_id="SOURCE-001")
    results.record(
        "Edge Retrieved",
        len(edges) > 0 and edges[0]["target"] == "TARGET-001"
    )
    
    return kg


async def test_graph_company_relationships(results: TestResults, kg: KnowledgeGraph):
    """Test company relationships loaded from Digital Twin."""
    print("\n🏢 TEST: Company Relationships")
    print("-" * 40)
    
    # Check company node exists
    company = kg.db.get_node("MAHA-LAKSHMI-CORP")
    results.record(
        "Company Node Exists",
        company is not None
    )
    
    # Check CEO node exists
    ceo = kg.db.get_node("CEO-PAK-PUR")
    results.record(
        "CEO Node Exists",
        ceo is not None
    )
    
    # Check SBU nodes exist
    sbu_nodes = kg.db.get_nodes_by_type(NodeType.SBU)
    results.record(
        "SBU Nodes Exist",
        len(sbu_nodes) >= 1
    )
    
    # Check CEO owns company relationship
    edges = kg.db.get_edges(source_id="CEO-PAK-PUR")
    ceo_owns = [e for e in edges if e.relation_type == RelationType.OWNS]
    results.record(
        "CEO OWNS Company Edge",
        len(ceo_owns) > 0
    )
    
    return kg


async def test_graph_revenue_relationships(results: TestResults, kg: KnowledgeGraph):
    """Test revenue relationships."""
    print("\n💰 TEST: Revenue Relationships")
    print("-" * 40)
    
    # Check Revenue Engine node exists
    revenue_engine = kg.db.get_node("REVENUE-ENGINE")
    results.record(
        "Revenue Engine Node Exists",
        revenue_engine is not None
    )
    
    # Check Revenue linked to Company
    edges = kg.db.get_edges(source_id="REVENUE-ENGINE")
    linked_to_company = [e for e in edges if e.relation_type == RelationType.GENERATED_BY]
    results.record(
        "Revenue Generated By Company",
        len(linked_to_company) > 0
    )
    
    # Check CEO share relationship
    owed_edges = [e for e in edges if e.relation_type == RelationType.OWED_TO]
    results.record(
        "CEO Owed Relationship Exists",
        len(owed_edges) > 0
    )
    
    if owed_edges:
        results.record(
            "CEO Share is 60%",
            owed_edges[0].weight == 0.6
        )
    
    return kg


async def test_graph_product_relationships(results: TestResults, kg: KnowledgeGraph):
    """Test product relationships."""
    print("\n🏪 TEST: Product Relationships")
    print("-" * 40)
    
    # Get all product nodes
    products = kg.db.get_nodes_by_type(NodeType.PRODUCT)
    
    results.record(
        "Products Loaded",
        len(products) >= 0  # May be empty if no products exist yet
    )
    
    # If products exist, verify relationships
    for product in products[:1]:  # Check first product
        edges = kg.db.get_edges(source_id=product.node_id)
        results.record(
            f"Product '{product.name}' has edges",
            len(edges) > 0
        )
    
    return kg


async def test_graph_query(results: TestResults, kg: KnowledgeGraph):
    """Test graph query operations."""
    print("\n🔍 TEST: Graph Query Operations")
    print("-" * 40)
    
    # Query by relation type
    query_result = kg.query(relation_type=RelationType.OWNS)
    results.record(
        "Query by Relation Type Works",
        len(query_result) > 0
    )
    
    # Query reachable nodes
    reachable = kg.query(start_node_id="MAHA-LAKSHMI-CORP", max_hops=2)
    results.record(
        "Query Reachable Nodes Works",
        len(reachable) > 0
    )
    
    # Get graph stats
    stats = kg.get_graph_stats()
    results.record(
        "Graph Stats Available",
        "total_nodes" in stats and "total_edges" in stats
    )
    
    results.record(
        "Graph Has Nodes",
        stats["total_nodes"] >= 3
    )
    
    return kg


async def test_github_center_initialization(results: TestResults):
    """Test GitHub center initialization."""
    print("\n🐙 TEST: GitHub Center Initialization")
    print("-" * 40)
    
    gh = get_github_center()
    
    results.record(
        "GitHub Center Created",
        gh is not None
    )
    
    results.record(
        "Database Initialized",
        gh.db is not None
    )
    
    return gh


async def test_github_status(results: TestResults, gh: GitHubCenter):
    """Test git status retrieval."""
    print("\n📊 TEST: Git Status")
    print("-" * 40)
    
    status = gh.get_status()
    
    results.record(
        "Status Retrieved",
        status is not None
    )
    
    results.record(
        "Has Current Branch",
        status.current_branch != "" or "Not a git" in str(status.conflicts)
    )
    
    results.record(
        "Has Sync Info",
        hasattr(status, 'ahead') and hasattr(status, 'behind')
    )
    
    return gh


async def test_github_branches(results: TestResults, gh: GitHubCenter):
    """Test git branch operations."""
    print("\n🌿 TEST: Git Branch Operations")
    print("-" * 40)
    
    branches = gh.get_branches()
    
    results.record(
        "Branches Retrieved",
        isinstance(branches, list)
    )
    
    results.record(
        "Branch List Works",
        True  # May be empty if no local branches
    )
    
    # Get remote branches
    remote_branches = gh.get_branches(remote=True)
    results.record(
        "Remote Branches Retrieved",
        isinstance(remote_branches, list)
    )
    
    return gh


async def test_github_remote_info(results: TestResults, gh: GitHubCenter):
    """Test remote repository info."""
    print("\n🌐 TEST: Git Remote Info")
    print("-" * 40)
    
    remote_info = gh.get_remote_info()
    
    results.record(
        "Remote Info Retrieved",
        "remotes" in remote_info
    )
    
    results.record(
        "Has Origin URL",
        "origin_url" in remote_info
    )
    
    return gh


async def test_github_conflict_detection(results: TestResults, gh: GitHubCenter):
    """Test conflict detection."""
    print("\n⚠️ TEST: Conflict Detection")
    print("-" * 40)
    
    conflicts = gh.detect_conflicts()
    
    results.record(
        "Conflict Detection Works",
        isinstance(conflicts, list)
    )
    
    results.record(
        "No Conflicts (expected)",
        len(conflicts) == 0
    )
    
    return gh


async def test_github_sync(results: TestResults, gh: GitHubCenter):
    """Test sync with remote."""
    print("\n🔄 TEST: Git Sync")
    print("-" * 40)
    
    sync_result = gh.sync_with_remote()
    
    results.record(
        "Sync Completed",
        "steps" in sync_result
    )
    
    results.record(
        "Has Final Status",
        "final_status" in sync_result
    )
    
    return gh


async def test_github_history(results: TestResults, gh: GitHubCenter):
    """Test operation history."""
    print("\n📜 TEST: Git Operation History")
    print("-" * 40)
    
    history = gh.get_operation_history()
    
    results.record(
        "History Retrieved",
        isinstance(history, list)
    )
    
    return gh


async def run_all_tests():
    """Run all tests."""
    print("\n" + "="*60)
    print("🤖 MAHALAKSMI AIOS v1.0.6 - Knowledge Graph & GitHub Tests")
    print("="*60)
    
    results = TestResults()
    
    try:
        # Knowledge Graph tests
        kg = await test_knowledge_graph_initialization(results)
        await test_graph_nodes_creation(results, kg)
        await test_graph_edges_creation(results, kg)
        await test_graph_company_relationships(results, kg)
        await test_graph_revenue_relationships(results, kg)
        await test_graph_product_relationships(results, kg)
        await test_graph_query(results, kg)
        
        # GitHub Center tests
        gh = await test_github_center_initialization(results)
        await test_github_status(results, gh)
        await test_github_branches(results, gh)
        await test_github_remote_info(results, gh)
        await test_github_conflict_detection(results, gh)
        await test_github_sync(results, gh)
        await test_github_history(results, gh)
        
    except Exception as e:
        print(f"\n❌ Test suite error: {e}")
        import traceback
        traceback.print_exc()
        results.failed += 1
    
    # Print summary
    print("\n" + "="*60)
    print(f"RESULTS: {results.passed} passed, {results.failed} failed")
    if results.errors:
        print("\nErrors:")
        for e in results.errors:
            print(f"  - {e}")
    print("="*60)
    
    success = results.failed == 0
    
    print("\n" + "="*60)
    if success:
        print("🎉 ALL TESTS PASSED!")
    else:
        print("⚠️ SOME TESTS FAILED - Review above")
    print("="*60)
    
    return success


if __name__ == "__main__":
    success = asyncio.run(run_all_tests())
    sys.exit(0 if success else 1)
